### ISSUE TITLE
bloxroute not available

### ISSUE THREAD

**Issue by lonely1215225** [ManofDiligence/Solana-Memecoin-CLI#23]
![image](https://github.com/user-attachments/assets/0d2267b1-ad65-4ce8-b09c-3f318954872c)

Teacher, is there any use case of bloxroute?

**Comment by outsmartchad** [comment]
Please Go to bloXroute account portal to get the auth header and paste in the .env, go to https://docs.bloxroute.com/apis/authorization-headers. i wrote a example in swap.ts in raydium/Pool/swap.ts, you can see i comment it, you can uncomment and try after you set your auth header in .env

**Comment by lonely1215225** [comment]
> Please Go to bloXroute account portal to get the auth header and paste in the .env, go to https://docs.bloxroute.com/apis/authorization-headers. i wrote a example in swap.ts in raydium/Pool/swap.ts, you can see i comment it, you can uncomment and try after you set your auth header in .env

thanks a lot！
